/*
 * Copyright 2026 the restxop contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.restxop.testkit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.sun.net.httpserver.HttpServer;
import dev.restxop.Attachment;
import dev.restxop.RestxopConfig;
import dev.restxop.core.internal.buffer.FileSpoolStorage;
import dev.restxop.core.internal.exchange.Exchange;
import dev.restxop.core.internal.read.MessageReader;
import dev.restxop.core.internal.read.ReadResult;
import dev.restxop.core.internal.write.MessageWriter;
import dev.restxop.spi.ResolvableTypeInfo;
import dev.restxop.spi.RootPartCodec;
import dev.restxop.testkit.model.ReportPayload;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URL;
import java.util.List;
import java.util.SplittableRandom;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * SC-006 throughput guard (tag {@code perf}, informational in CI): a
 * 100 MB attachment through the full restxop stack over loopback must stay
 * within 50% of copying the same bytes over a plain streamed HTTP response
 * measured by this same harness — i.e. the library adds at most 2x
 * overhead. The legacy per-byte design was orders of magnitude off this
 * mark; the buffered scanner and bulk chase-buffer paths are what this
 * guards.
 */
@Tag("perf")
@Timeout(600)
public abstract class ThroughputHarness {

    private static final String CONTENT_TYPE = "Content-Type";

    private static final Logger log = LoggerFactory.getLogger(ThroughputHarness.class);

    protected static final long TRANSFER_BYTES =
            Long.getLong("restxop.perf.bytes", 100L * 1024 * 1024);
    private static final int ROUNDS = 3;
    private static final long SEED = 20260705;

    /** The codec under test; protocol throughput does not depend on it. */
    protected RootPartCodec codec() {
        return new StubRootPartCodec();
    }

    private HttpServer server;
    private MessageReader reader;
    private ListenerCapture capture;

    @BeforeEach
    void startServer() throws IOException {
        server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);

        // Plain streamed HTTP baseline: raw generated bytes, chunked like
        // any streamed response of unknown length (the case restxop serves)
        server.createContext("/plain", httpExchange -> {
            httpExchange.getResponseHeaders().set(CONTENT_TYPE, "application/octet-stream");
            httpExchange.sendResponseHeaders(200, 0);
            try (OutputStream out = httpExchange.getResponseBody()) {
                copyGenerated(out);
            }
        });

        // The same bytes as a restxop message
        server.createContext("/restxop", httpExchange -> {
            MessageWriter writer = new MessageWriter(RestxopConfig.defaults(), codec());
            httpExchange.getResponseHeaders().set(CONTENT_TYPE, writer.contentType());
            httpExchange.sendResponseHeaders(200, 0);
            Exchange exchange = Exchange.open(RestxopConfig.defaults(), List.of());
            try (OutputStream out = httpExchange.getResponseBody()) {
                ReportPayload payload = new ReportPayload("perf",
                        Attachment.builder(new GeneratedStream())
                                .contentLength(TRANSFER_BYTES)
                                .build());
                writer.write(exchange, payload, out);
                exchange.complete();
            } catch (IOException | RuntimeException e) {
                exchange.fail(e);
                throw e;
            }
        });

        server.start();
        capture = new ListenerCapture();
        reader = new MessageReader(RestxopConfig.defaults(), codec(), new FileSpoolStorage(),
                List.of(capture));
    }

    @AfterEach
    void stopServer() {
        server.stop(0);
        reader.close();
    }

    @Test
    protected void restxopStaysWithinTwiceThePlainHttpBaseline() throws IOException {
        // Warm-up (JIT, connection setup) — one round each, unmeasured
        runPlain();
        runRestxop();

        long plainBest = Long.MAX_VALUE;
        long restxopBest = Long.MAX_VALUE;
        for (int i = 0; i < ROUNDS; i++) {
            plainBest = Math.min(plainBest, runPlain());
            restxopBest = Math.min(restxopBest, runRestxop());
        }

        double plainMbps = megabytesPerSecond(plainBest);
        double restxopMbps = megabytesPerSecond(restxopBest);
        String plainSummary = String.format("%.0f", plainMbps);
        String restxopSummary = String.format("%.0f", restxopMbps);
        String ratio = String.format("%.2f", (double) restxopBest / plainBest);
        log.info("SC-006 throughput: plain HTTP {} ms ({} MB/s), restxop {} ms ({} MB/s), "
                        + "ratio {}",
                plainBest, plainSummary, restxopBest, restxopSummary, ratio);
        log.info("SC-006 spool activity: max {} bytes spooled per part", capture.maxSpooled());

        assertTrue(restxopBest <= 2 * plainBest,
                "restxop must stay within 50% of the plain streamed baseline (SC-006): "
                        + "plain " + plainBest + " ms vs restxop " + restxopBest + " ms");
    }

    private long runPlain() throws IOException {
        long start = System.nanoTime();
        URL url = URI.create("http://127.0.0.1:" + server.getAddress().getPort() + "/plain").toURL();
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        long total = 0;
        byte[] buffer = new byte[64 * 1024];
        try (InputStream in = connection.getInputStream()) {
            int n;
            while ((n = in.read(buffer)) != -1) {
                total += n;
            }
        }
        assertEquals(TRANSFER_BYTES, total);
        return (System.nanoTime() - start) / 1_000_000;
    }

    private long runRestxop() throws IOException {
        long start = System.nanoTime();
        URL url = URI.create("http://127.0.0.1:" + server.getAddress().getPort() + "/restxop").toURL();
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        long total = 0;
        byte[] buffer = new byte[64 * 1024];
        try (InputStream in = connection.getInputStream()) {
            ReadResult<ReportPayload> result = reader.read(
                    connection.getHeaderField(CONTENT_TYPE), in,
                    ResolvableTypeInfo.of(ReportPayload.class), null);
            try (InputStream attachment = result.payload().report.contentStream()) {
                int n;
                while ((n = attachment.read(buffer)) != -1) {
                    total += n;
                }
            }
        }
        assertEquals(TRANSFER_BYTES, total);
        return (System.nanoTime() - start) / 1_000_000;
    }

    private static double megabytesPerSecond(long millis) {
        return (TRANSFER_BYTES / (1024.0 * 1024.0)) / (millis / 1000.0);
    }

    private static void copyGenerated(OutputStream out) throws IOException {
        byte[] buffer = new byte[64 * 1024];
        try (GeneratedStream in = new GeneratedStream()) {
            int n;
            while ((n = in.read(buffer, 0, buffer.length)) != -1) {
                out.write(buffer, 0, n);
            }
        }
    }

    /** Deterministic pseudo-random content without materializing it. */
    private static final class GeneratedStream extends InputStream {

        private final SplittableRandom random = new SplittableRandom(SEED);
        private long remaining = TRANSFER_BYTES;

        @Override
        public int read() {
            byte[] one = new byte[1];
            return read(one, 0, 1) < 0 ? -1 : one[0] & 0xFF;
        }

        @Override
        public int read(byte[] buffer, int off, int len) {
            if (remaining <= 0) {
                return -1;
            }
            int n = (int) Math.min(len, remaining);
            for (int i = 0; i < n; i += 8) {
                long value = random.nextLong();
                for (int j = i; j < Math.min(i + 8, n); j++) {
                    buffer[off + j] = (byte) value;
                    value >>>= 8;
                }
            }
            remaining -= n;
            return n;
        }
    }
}
