version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/restxop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
    reviewers:
      - "jshipman42"

  - package-ecosystem: "npm"
    directories:
      - "/restxop-js"
      - "/restxop-js/demo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
      security:
        applies-to: security-updates
        patterns:
          - "*"
    reviewers:
      - "jshipman42"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
