sonar.projectKey=restxop_restxop-js
sonar.organization=restxop
sonar.projectName=restxop-js

sonar.sources=src
sonar.tests=test
sonar.exclusions=dist/**,demo/**,scripts/**,node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
